import {CardType} from "./types.ts";

export const starterBeelzemon: CardType[] = [
    {
        "name": "Yaamon",
        "type": "Digi-Egg",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-01.jpg",
        "cardnumber": "ST14-01",
        "stage": "In-Training",
        "digi_type": "Lesser",
        "level": 2,
        "soureeffect": "[When Attacking] [Once Per Turn] If this Digimon has the [Wizard]/[Demon Lord] trait, trash the top 2 cards of your deck."
    },
    {
        "name": "Yaamon",
        "type": "Digi-Egg",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-01.jpg",
        "cardnumber": "ST14-01",
        "stage": "In-Training",
        "digi_type": "Lesser",
        "level": 2,
        "soureeffect": "[When Attacking] [Once Per Turn] If this Digimon has the [Wizard]/[Demon Lord] trait, trash the top 2 cards of your deck."
    },
    {
        "name": "Yaamon",
        "type": "Digi-Egg",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-01.jpg",
        "cardnumber": "ST14-01",
        "stage": "In-Training",
        "digi_type": "Lesser",
        "level": 2,
        "soureeffect": "[When Attacking] [Once Per Turn] If this Digimon has the [Wizard]/[Demon Lord] trait, trash the top 2 cards of your deck."
    },
    {
        "name": "Yaamon",
        "type": "Digi-Egg",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-01.jpg",
        "cardnumber": "ST14-01",
        "stage": "In-Training",
        "digi_type": "Lesser",
        "level": 2,
        "soureeffect": "[When Attacking] [Once Per Turn] If this Digimon has the [Wizard]/[Demon Lord] trait, trash the top 2 cards of your deck."
    },
    {
        "name": "Death Slinger",
        "type": "Option",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/EX2-071.jpg",
        "cardnumber": "EX2-071",
        "play_cost": 4,
        "maineffect": "When this card is trashed from your deck, gain 1 memory. [Main] Delete 1 of your opponent's level 4 or lower Digimon. For every 10 cards in your trash, add 1 to the maximum level of the Digimon you can choose with this effect.",
        "soureeffect": "[Security] Activate this card's [Main] effect."
    },
    {
        "name": "Death Slinger",
        "type": "Option",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/EX2-071.jpg",
        "cardnumber": "EX2-071",
        "play_cost": 4,
        "maineffect": "When this card is trashed from your deck, gain 1 memory. [Main] Delete 1 of your opponent's level 4 or lower Digimon. For every 10 cards in your trash, add 1 to the maximum level of the Digimon you can choose with this effect.",
        "soureeffect": "[Security] Activate this card's [Main] effect."
    },
    {
        "name": "Death Slinger",
        "type": "Option",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/EX2-071.jpg",
        "cardnumber": "EX2-071",
        "play_cost": 4,
        "maineffect": "When this card is trashed from your deck, gain 1 memory. [Main] Delete 1 of your opponent's level 4 or lower Digimon. For every 10 cards in your trash, add 1 to the maximum level of the Digimon you can choose with this effect.",
        "soureeffect": "[Security] Activate this card's [Main] effect."
    },
    {
        "name": "Death Slinger",
        "type": "Option",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/EX2-071.jpg",
        "cardnumber": "EX2-071",
        "play_cost": 4,
        "maineffect": "When this card is trashed from your deck, gain 1 memory. [Main] Delete 1 of your opponent's level 4 or lower Digimon. For every 10 cards in your trash, add 1 to the maximum level of the Digimon you can choose with this effect.",
        "soureeffect": "[Security] Activate this card's [Main] effect."
    },
    {
        "name": "Rivals' Barrage",
        "type": "Option",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-12.jpg",
        "cardnumber": "ST14-12",
        "play_cost": 7,
        "maineffect": "When this card is trashed from your deck, you may place it in the battle area. [Main] Delete 1 of your opponent's Digimon with the highest level. [Main] ＜Delay＞ (Trash this card in your battle area to activate the effect below. You can't activate this effect the turn this card enters play.). ・Return 1 purple Digimon card or Tamer card from your trash to your hand.",
        "soureeffect": "[Security] Delete 1 of your opponent's Digimon with the highest level."
    },
    {
        "name": "Rivals' Barrage",
        "type": "Option",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-12.jpg",
        "cardnumber": "ST14-12",
        "play_cost": 7,
        "maineffect": "When this card is trashed from your deck, you may place it in the battle area. [Main] Delete 1 of your opponent's Digimon with the highest level. [Main] ＜Delay＞ (Trash this card in your battle area to activate the effect below. You can't activate this effect the turn this card enters play.). ・Return 1 purple Digimon card or Tamer card from your trash to your hand.",
        "soureeffect": "[Security] Delete 1 of your opponent's Digimon with the highest level."
    },
    {
        "name": "Ai & Mako",
        "type": "Tamer",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-11.jpg",
        "cardnumber": "ST14-11",
        "play_cost": 3,
        "maineffect": "[On Play] Reveal the top 4 cards of your deck. Add 1 Digimon card with the [Evil]/[Wizard]/[Demon Lord] trait among them to your hand. Place the rest at the bottom of your deck in any order. [Your Turn] When one of your Digimon digivolves into a purple Digimon, by suspending this Tamer, return 1 card from your hand to the top of your deck and gain 1 memory.",
        "soureeffect": "[Security] Play this card without paying its memory cost."
    },
    {
        "name": "Ai & Mako",
        "type": "Tamer",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-11.jpg",
        "cardnumber": "ST14-11",
        "play_cost": 3,
        "maineffect": "[On Play] Reveal the top 4 cards of your deck. Add 1 Digimon card with the [Evil]/[Wizard]/[Demon Lord] trait among them to your hand. Place the rest at the bottom of your deck in any order. [Your Turn] When one of your Digimon digivolves into a purple Digimon, by suspending this Tamer, return 1 card from your hand to the top of your deck and gain 1 memory.",
        "soureeffect": "[Security] Play this card without paying its memory cost."
    },
    {
        "name": "Ai & Mako",
        "type": "Tamer",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-11.jpg",
        "cardnumber": "ST14-11",
        "play_cost": 3,
        "maineffect": "[On Play] Reveal the top 4 cards of your deck. Add 1 Digimon card with the [Evil]/[Wizard]/[Demon Lord] trait among them to your hand. Place the rest at the bottom of your deck in any order. [Your Turn] When one of your Digimon digivolves into a purple Digimon, by suspending this Tamer, return 1 card from your hand to the top of your deck and gain 1 memory.",
        "soureeffect": "[Security] Play this card without paying its memory cost."
    },
    {
        "name": "Ai & Mako",
        "type": "Tamer",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-11.jpg",
        "cardnumber": "ST14-11",
        "play_cost": 3,
        "maineffect": "[On Play] Reveal the top 4 cards of your deck. Add 1 Digimon card with the [Evil]/[Wizard]/[Demon Lord] trait among them to your hand. Place the rest at the bottom of your deck in any order. [Your Turn] When one of your Digimon digivolves into a purple Digimon, by suspending this Tamer, return 1 card from your hand to the top of your deck and gain 1 memory.",
        "soureeffect": "[Security] Play this card without paying its memory cost."
    },
    {
        "name": "Phascomon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-04.jpg",
        "cardnumber": "ST14-04",
        "attribute": "Virus",
        "digi_type": "Dark Animal",
        "dp": 2000,
        "play_cost": 3,
        "maineffect": "＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target). [Your Turn] This Digimon can't attack players."
    },
    {
        "name": "Phascomon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-04.jpg",
        "cardnumber": "ST14-04",
        "attribute": "Virus",
        "digi_type": "Dark Animal",
        "dp": 2000,
        "play_cost": 3,
        "maineffect": "＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target). [Your Turn] This Digimon can't attack players."
    },
    {
        "name": "Phascomon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-04.jpg",
        "cardnumber": "ST14-04",
        "attribute": "Virus",
        "digi_type": "Dark Animal",
        "dp": 2000,
        "play_cost": 3,
        "maineffect": "＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target). [Your Turn] This Digimon can't attack players."
    },
    {
        "name": "Phascomon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-04.jpg",
        "cardnumber": "ST14-04",
        "attribute": "Virus",
        "digi_type": "Dark Animal",
        "dp": 2000,
        "play_cost": 3,
        "maineffect": "＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target). [Your Turn] This Digimon can't attack players."
    },
    {
        "name": "Impmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/BT2-068.jpg",
        "cardnumber": "BT2-068",
        "stage": "Rookie",
        "attribute": "Virus",
        "digi_type": "Evil",
        "dp": 1000,
        "play_cost": 3,
        "evolution_cost": 0,
        "level": 3,
        "maineffect": "[On Deletion] Trash the top 3 cards of your deck."
    },
    {
        "name": "Impmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/BT2-068.jpg",
        "cardnumber": "BT2-068",
        "stage": "Rookie",
        "attribute": "Virus",
        "digi_type": "Evil",
        "dp": 1000,
        "play_cost": 3,
        "evolution_cost": 0,
        "level": 3,
        "maineffect": "[On Deletion] Trash the top 3 cards of your deck."
    },
    {
        "name": "Impmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/BT2-068.jpg",
        "cardnumber": "BT2-068",
        "stage": "Rookie",
        "attribute": "Virus",
        "digi_type": "Evil",
        "dp": 1000,
        "play_cost": 3,
        "evolution_cost": 0,
        "level": 3,
        "maineffect": "[On Deletion] Trash the top 3 cards of your deck."
    },
    {
        "name": "Impmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/BT2-068.jpg",
        "cardnumber": "BT2-068",
        "stage": "Rookie",
        "attribute": "Virus",
        "digi_type": "Evil",
        "dp": 1000,
        "play_cost": 3,
        "evolution_cost": 0,
        "level": 3,
        "maineffect": "[On Deletion] Trash the top 3 cards of your deck."
    },
    {
        "name": "Impmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-02.jpg",
        "cardnumber": "ST14-02",
        "stage": "Rookie",
        "attribute": "Virus",
        "digi_type": "Evil",
        "dp": 1000,
        "play_cost": 3,
        "evolution_cost": 0,
        "level": 3,
        "maineffect": "[When Attacking] If you have 20 or more cards in your trash, this Digimon may digivolve into [Beelzemon] from your trash for a digivolution cost of 3, ignoring its digivolution requirements.",
        "soureeffect": "[Your Turn] [Once Per Turn] When a card is trashed from your deck, delete 1 of your opponent's level 3 Digimon."
    },
    {
        "name": "Impmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-02.jpg",
        "cardnumber": "ST14-02",
        "stage": "Rookie",
        "attribute": "Virus",
        "digi_type": "Evil",
        "dp": 1000,
        "play_cost": 3,
        "evolution_cost": 0,
        "level": 3,
        "maineffect": "[When Attacking] If you have 20 or more cards in your trash, this Digimon may digivolve into [Beelzemon] from your trash for a digivolution cost of 3, ignoring its digivolution requirements.",
        "soureeffect": "[Your Turn] [Once Per Turn] When a card is trashed from your deck, delete 1 of your opponent's level 3 Digimon."
    },
    {
        "name": "Candlemon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-03.jpg",
        "cardnumber": "ST14-03",
        "stage": "Rookie",
        "attribute": "Data",
        "digi_type": "Flame",
        "dp": 1000,
        "play_cost": 3,
        "evolution_cost": 0,
        "level": 3,
        "maineffect": "[On Play] Trash the top 2 cards of your deck. [On Deletion] If you have 10 or more cards in your trash, ＜Draw 1＞ (Draw 1 card from your deck)."
    },
    {
        "name": "Candlemon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-03.jpg",
        "cardnumber": "ST14-03",
        "stage": "Rookie",
        "attribute": "Data",
        "digi_type": "Flame",
        "dp": 1000,
        "play_cost": 3,
        "evolution_cost": 0,
        "level": 3,
        "maineffect": "[On Play] Trash the top 2 cards of your deck. [On Deletion] If you have 10 or more cards in your trash, ＜Draw 1＞ (Draw 1 card from your deck)."
    },
    {
        "name": "Candlemon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-03.jpg",
        "cardnumber": "ST14-03",
        "stage": "Rookie",
        "attribute": "Data",
        "digi_type": "Flame",
        "dp": 1000,
        "play_cost": 3,
        "evolution_cost": 0,
        "level": 3,
        "maineffect": "[On Play] Trash the top 2 cards of your deck. [On Deletion] If you have 10 or more cards in your trash, ＜Draw 1＞ (Draw 1 card from your deck)."
    },
    {
        "name": "Candlemon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-03.jpg",
        "cardnumber": "ST14-03",
        "stage": "Rookie",
        "attribute": "Data",
        "digi_type": "Flame",
        "dp": 1000,
        "play_cost": 3,
        "evolution_cost": 0,
        "level": 3,
        "maineffect": "[On Play] Trash the top 2 cards of your deck. [On Deletion] If you have 10 or more cards in your trash, ＜Draw 1＞ (Draw 1 card from your deck)."
    },
    {
        "name": "Wizardmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/P-077.jpg",
        "cardnumber": "P-077",
        "stage": "Champion",
        "attribute": "Data",
        "digi_type": "Wizard",
        "dp": 5000,
        "play_cost": 5,
        "evolution_cost": 2,
        "level": 4,
        "maineffect": "When this card is trashed from your Deck, gain 1 memory.",
        "soureeffect": "[When Attacking] You may reveal 1 purple card from your hand and place it on top of your deck."
    },
    {
        "name": "Wizardmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/P-077.jpg",
        "cardnumber": "P-077",
        "stage": "Champion",
        "attribute": "Data",
        "digi_type": "Wizard",
        "dp": 5000,
        "play_cost": 5,
        "evolution_cost": 2,
        "level": 4,
        "maineffect": "When this card is trashed from your Deck, gain 1 memory.",
        "soureeffect": "[When Attacking] You may reveal 1 purple card from your hand and place it on top of your deck."
    },
    {
        "name": "Wizardmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/P-077.jpg",
        "cardnumber": "P-077",
        "stage": "Champion",
        "attribute": "Data",
        "digi_type": "Wizard",
        "dp": 5000,
        "play_cost": 5,
        "evolution_cost": 2,
        "level": 4,
        "maineffect": "When this card is trashed from your Deck, gain 1 memory.",
        "soureeffect": "[When Attacking] You may reveal 1 purple card from your hand and place it on top of your deck."
    },
    {
        "name": "Wizardmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/P-077.jpg",
        "cardnumber": "P-077",
        "stage": "Champion",
        "attribute": "Data",
        "digi_type": "Wizard",
        "dp": 5000,
        "play_cost": 5,
        "evolution_cost": 2,
        "level": 4,
        "maineffect": "When this card is trashed from your Deck, gain 1 memory.",
        "soureeffect": "[When Attacking] You may reveal 1 purple card from your hand and place it on top of your deck."
    },
    {
        "name": "Porcupamon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-05.jpg",
        "cardnumber": "ST14-05",
        "stage": "Champion",
        "attribute": "Virus",
        "digi_type": "Puppet",
        "dp": 4000,
        "play_cost": 4,
        "evolution_cost": 2,
        "level": 4,
        "maineffect": "＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target). [On Play] Trash the top 2 cards of your deck."
    },
    {
        "name": "Porcupamon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-05.jpg",
        "cardnumber": "ST14-05",
        "stage": "Champion",
        "attribute": "Virus",
        "digi_type": "Puppet",
        "dp": 4000,
        "play_cost": 4,
        "evolution_cost": 2,
        "level": 4,
        "maineffect": "＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target). [On Play] Trash the top 2 cards of your deck."
    },
    {
        "name": "Porcupamon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-05.jpg",
        "cardnumber": "ST14-05",
        "stage": "Champion",
        "attribute": "Virus",
        "digi_type": "Puppet",
        "dp": 4000,
        "play_cost": 4,
        "evolution_cost": 2,
        "level": 4,
        "maineffect": "＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target). [On Play] Trash the top 2 cards of your deck."
    },
    {
        "name": "Porcupamon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-05.jpg",
        "cardnumber": "ST14-05",
        "stage": "Champion",
        "attribute": "Virus",
        "digi_type": "Puppet",
        "dp": 4000,
        "play_cost": 4,
        "evolution_cost": 2,
        "level": 4,
        "maineffect": "＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target). [On Play] Trash the top 2 cards of your deck."
    },
    {
        "name": "Witchmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-06.jpg",
        "cardnumber": "ST14-06",
        "stage": "Champion",
        "digi_type": "Wizard",
        "dp": 5000,
        "play_cost": 5,
        "evolution_cost": 2,
        "level": 4,
        "maineffect": "[When Digivolving] Trash the top 3 cards of your deck.",
        "soureeffect": "[Your Turn] While this Digimon has [Wizard]/[Demon Lord], it gets +2000 DP."
    },
    {
        "name": "Witchmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-06.jpg",
        "cardnumber": "ST14-06",
        "stage": "Champion",
        "digi_type": "Wizard",
        "dp": 5000,
        "play_cost": 5,
        "evolution_cost": 2,
        "level": 4,
        "maineffect": "[When Digivolving] Trash the top 3 cards of your deck.",
        "soureeffect": "[Your Turn] While this Digimon has [Wizard]/[Demon Lord], it gets +2000 DP."
    },
    {
        "name": "Witchmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-06.jpg",
        "cardnumber": "ST14-06",
        "stage": "Champion",
        "digi_type": "Wizard",
        "dp": 5000,
        "play_cost": 5,
        "evolution_cost": 2,
        "level": 4,
        "maineffect": "[When Digivolving] Trash the top 3 cards of your deck.",
        "soureeffect": "[Your Turn] While this Digimon has [Wizard]/[Demon Lord], it gets +2000 DP."
    },
    {
        "name": "Witchmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-06.jpg",
        "cardnumber": "ST14-06",
        "stage": "Champion",
        "digi_type": "Wizard",
        "dp": 5000,
        "play_cost": 5,
        "evolution_cost": 2,
        "level": 4,
        "maineffect": "[When Digivolving] Trash the top 3 cards of your deck.",
        "soureeffect": "[Your Turn] While this Digimon has [Wizard]/[Demon Lord], it gets +2000 DP."
    },
    {
        "name": "SkullSatamon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/BT8-079.jpg",
        "cardnumber": "BT8-079",
        "stage": "Ultimate",
        "attribute": "Virus",
        "digi_type": "Undead",
        "dp": 7000,
        "play_cost": 7,
        "evolution_cost": 3,
        "level": 5,
        "maineffect": "[When Digivolving] Trash the top 2 cards of your deck. Then, return 1 card with the [Demon Lord] trait from your trash to your hand.",
        "soureeffect": "[Your Turn] [Once Per Turn] When a card is trashed from your deck, gain 1 memory."
    },
    {
        "name": "SkullSatamon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/BT8-079.jpg",
        "cardnumber": "BT8-079",
        "stage": "Ultimate",
        "attribute": "Virus",
        "digi_type": "Undead",
        "dp": 7000,
        "play_cost": 7,
        "evolution_cost": 3,
        "level": 5,
        "maineffect": "[When Digivolving] Trash the top 2 cards of your deck. Then, return 1 card with the [Demon Lord] trait from your trash to your hand.",
        "soureeffect": "[Your Turn] [Once Per Turn] When a card is trashed from your deck, gain 1 memory."
    },
    {
        "name": "SkullSatamon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/BT8-079.jpg",
        "cardnumber": "BT8-079",
        "stage": "Ultimate",
        "attribute": "Virus",
        "digi_type": "Undead",
        "dp": 7000,
        "play_cost": 7,
        "evolution_cost": 3,
        "level": 5,
        "maineffect": "[When Digivolving] Trash the top 2 cards of your deck. Then, return 1 card with the [Demon Lord] trait from your trash to your hand.",
        "soureeffect": "[Your Turn] [Once Per Turn] When a card is trashed from your deck, gain 1 memory."
    },
    {
        "name": "SkullSatamon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/BT8-079.jpg",
        "cardnumber": "BT8-079",
        "stage": "Ultimate",
        "attribute": "Virus",
        "digi_type": "Undead",
        "dp": 7000,
        "play_cost": 7,
        "evolution_cost": 3,
        "level": 5,
        "maineffect": "[When Digivolving] Trash the top 2 cards of your deck. Then, return 1 card with the [Demon Lord] trait from your trash to your hand.",
        "soureeffect": "[Your Turn] [Once Per Turn] When a card is trashed from your deck, gain 1 memory."
    },
    {
        "name": "Baalmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-07.jpg",
        "cardnumber": "ST14-07",
        "stage": "Ultimate",
        "attribute": "Free",
        "digi_type": "Wizard",
        "dp": 7000,
        "play_cost": 7,
        "evolution_cost": 3,
        "level": 5,
        "maineffect": "[When Digivolving] Trash the top 3 cards of your deck. [When Digivolving] This Digimon gains \"[On Deletion] If there are 10 or more cards in your trash, you may play 1 [Beelzemon] from your trash without paying the cost\" until the end of your opponent's turn.",
        "soureeffect": "[Your Turn] While this Digimon has the [Wizard]/[Demon Lord] trait, it gets +2000 DP."
    },
    {
        "name": "Baalmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-07.jpg",
        "cardnumber": "ST14-07",
        "stage": "Ultimate",
        "attribute": "Free",
        "digi_type": "Wizard",
        "dp": 7000,
        "play_cost": 7,
        "evolution_cost": 3,
        "level": 5,
        "maineffect": "[When Digivolving] Trash the top 3 cards of your deck. [When Digivolving] This Digimon gains \"[On Deletion] If there are 10 or more cards in your trash, you may play 1 [Beelzemon] from your trash without paying the cost\" until the end of your opponent's turn.",
        "soureeffect": "[Your Turn] While this Digimon has the [Wizard]/[Demon Lord] trait, it gets +2000 DP."
    },
    {
        "name": "Baalmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-07.jpg",
        "cardnumber": "ST14-07",
        "stage": "Ultimate",
        "attribute": "Free",
        "digi_type": "Wizard",
        "dp": 7000,
        "play_cost": 7,
        "evolution_cost": 3,
        "level": 5,
        "maineffect": "[When Digivolving] Trash the top 3 cards of your deck. [When Digivolving] This Digimon gains \"[On Deletion] If there are 10 or more cards in your trash, you may play 1 [Beelzemon] from your trash without paying the cost\" until the end of your opponent's turn.",
        "soureeffect": "[Your Turn] While this Digimon has the [Wizard]/[Demon Lord] trait, it gets +2000 DP."
    },
    {
        "name": "Baalmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-07.jpg",
        "cardnumber": "ST14-07",
        "stage": "Ultimate",
        "attribute": "Free",
        "digi_type": "Wizard",
        "dp": 7000,
        "play_cost": 7,
        "evolution_cost": 3,
        "level": 5,
        "maineffect": "[When Digivolving] Trash the top 3 cards of your deck. [When Digivolving] This Digimon gains \"[On Deletion] If there are 10 or more cards in your trash, you may play 1 [Beelzemon] from your trash without paying the cost\" until the end of your opponent's turn.",
        "soureeffect": "[Your Turn] While this Digimon has the [Wizard]/[Demon Lord] trait, it gets +2000 DP."
    },
    {
        "name": "Beelzemon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-08.jpg",
        "cardnumber": "ST14-08",
        "stage": "Mega",
        "attribute": "Virus",
        "digi_type": "Demon Lord",
        "dp": 12000,
        "play_cost": 12,
        "evolution_cost": 4,
        "level": 6,
        "maineffect": "[When Digivolving] Trash the top 4 cards of your deck. [All Turns] [Once Per Turn] When a card is trashed from your deck, gain 1 memory for every 10 cards in your trash. [Your Turn] [Once Per Turn] When a card is trashed from your deck, this Digimon gains ＜Security Attack +1＞ (This Digimon checks 1 additional security card) for the turn."
    },
    {
        "name": "Beelzemon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-08.jpg",
        "cardnumber": "ST14-08",
        "stage": "Mega",
        "attribute": "Virus",
        "digi_type": "Demon Lord",
        "dp": 12000,
        "play_cost": 12,
        "evolution_cost": 4,
        "level": 6,
        "maineffect": "[When Digivolving] Trash the top 4 cards of your deck. [All Turns] [Once Per Turn] When a card is trashed from your deck, gain 1 memory for every 10 cards in your trash. [Your Turn] [Once Per Turn] When a card is trashed from your deck, this Digimon gains ＜Security Attack +1＞ (This Digimon checks 1 additional security card) for the turn."
    },
    {
        "name": "BeelStarmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-09.jpg",
        "cardnumber": "ST14-09",
        "stage": "Mega",
        "attribute": "Virus",
        "digi_type": "Wizard",
        "dp": 11000,
        "play_cost": 13,
        "level": 6,
        "maineffect": "When you would play this card from your hand, reduce the play cost by 4 for every 10 cards in your trash. [All Turns] [Once Per Turn] When a card is trashed from your deck, you may play 1 [Impmon] from your trash without paying the cost. The Digimon played by this effect gains ＜Rush＞ (This Digimon can attack the turn it comes into play) for the turn. [Opponent's Turn] When an opponent's Digimon attacks, trash the top card of your deck."
    },
    {
        "name": "BeelStarmon",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-09.jpg",
        "cardnumber": "ST14-09",
        "stage": "Mega",
        "attribute": "Virus",
        "digi_type": "Wizard",
        "dp": 11000,
        "play_cost": 13,
        "level": 6,
        "maineffect": "When you would play this card from your hand, reduce the play cost by 4 for every 10 cards in your trash. [All Turns] [Once Per Turn] When a card is trashed from your deck, you may play 1 [Impmon] from your trash without paying the cost. The Digimon played by this effect gains ＜Rush＞ (This Digimon can attack the turn it comes into play) for the turn. [Opponent's Turn] When an opponent's Digimon attacks, trash the top card of your deck."
    },
    {
        "name": "Beelzemon: Blast Mode",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-10.jpg",
        "cardnumber": "ST14-10",
        "stage": "Mega",
        "attribute": "Virus",
        "digi_type": "Demon Lord",
        "dp": 14000,
        "play_cost": 14,
        "evolution_cost": 4,
        "level": 7,
        "maineffect": "When this card is trashed from your deck, delete 1 of your opponent's level 3 or lower Digimon. For every 10 cards in your trash, add 1 to the maximum level of the Digimon you can choose with this effect. [When Digivolving] Unsuspend this Digimon. If you have 20 or more cards in your trash, gain 3 memory."
    },
    {
        "name": "Beelzemon: Blast Mode",
        "type": "Digimon",
        "color": "Purple",
        "image_url": "https://images.digimoncard.io/images/cards/ST14-10.jpg",
        "cardnumber": "ST14-10",
        "stage": "Mega",
        "attribute": "Virus",
        "digi_type": "Demon Lord",
        "dp": 14000,
        "play_cost": 14,
        "evolution_cost": 4,
        "level": 7,
        "maineffect": "When this card is trashed from your deck, delete 1 of your opponent's level 3 or lower Digimon. For every 10 cards in your trash, add 1 to the maximum level of the Digimon you can choose with this effect. [When Digivolving] Unsuspend this Digimon. If you have 20 or more cards in your trash, gain 3 memory."
    }
]

export const starterImperialdramon: CardType[] = [
        {
            "name": "Minomon",
            "type": "Digi-Egg",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-01.jpg",
            "cardnumber": "ST9-01",
            "stage": "In-Training",
            "digi_type": "Larva",
            "level": 2,
            "soureeffect": "[Your Turn] While you have a blue Digimon in play, this Digimon gets +1000 DP."
        },
        {
            "name": "Minomon",
            "type": "Digi-Egg",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-01.jpg",
            "cardnumber": "ST9-01",
            "stage": "In-Training",
            "digi_type": "Larva",
            "level": 2,
            "soureeffect": "[Your Turn] While you have a blue Digimon in play, this Digimon gets +1000 DP."
        },
        {
            "name": "Minomon",
            "type": "Digi-Egg",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-01.jpg",
            "cardnumber": "ST9-01",
            "stage": "In-Training",
            "digi_type": "Larva",
            "level": 2,
            "soureeffect": "[Your Turn] While you have a blue Digimon in play, this Digimon gets +1000 DP."
        },
        {
            "name": "Minomon",
            "type": "Digi-Egg",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-01.jpg",
            "cardnumber": "ST9-01",
            "stage": "In-Training",
            "digi_type": "Larva",
            "level": 2,
            "soureeffect": "[Your Turn] While you have a blue Digimon in play, this Digimon gets +1000 DP."
        },
        {
            "name": "Flower Cannon",
            "type": "Option",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/BT1-110.jpg",
            "cardnumber": "BT1-110",
            "play_cost": 2,
            "maineffect": "[Main] Suspend 1 of your opponent's Digimon.",
            "soureeffect": "[Security] Suspend all of your opponent's Digimon without ＜Blocker＞ ."
        },
        {
            "name": "Flower Cannon",
            "type": "Option",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/BT1-110.jpg",
            "cardnumber": "BT1-110",
            "play_cost": 2,
            "maineffect": "[Main] Suspend 1 of your opponent's Digimon.",
            "soureeffect": "[Security] Suspend all of your opponent's Digimon without ＜Blocker＞ ."
        },
        {
            "name": "Flower Cannon",
            "type": "Option",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/BT1-110.jpg",
            "cardnumber": "BT1-110",
            "play_cost": 2,
            "maineffect": "[Main] Suspend 1 of your opponent's Digimon.",
            "soureeffect": "[Security] Suspend all of your opponent's Digimon without ＜Blocker＞ ."
        },
        {
            "name": "Flower Cannon",
            "type": "Option",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/BT1-110.jpg",
            "cardnumber": "BT1-110",
            "play_cost": 2,
            "maineffect": "[Main] Suspend 1 of your opponent's Digimon.",
            "soureeffect": "[Security] Suspend all of your opponent's Digimon without ＜Blocker＞ ."
        },
        {
            "name": "Megadeath",
            "type": "Option",
            "color": "Blue",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-14.jpg",
            "cardnumber": "ST9-14",
            "play_cost": 5,
            "maineffect": "[Main] Suspend 1 of your opponents Digimon. Then, return 1 of your opponent's suspended Digimon to its owner's hand.",
            "soureeffect": "[Security] Activate this card's [Main] effect."
        },
        {
            "name": "Megadeath",
            "type": "Option",
            "color": "Blue",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-14.jpg",
            "cardnumber": "ST9-14",
            "play_cost": 5,
            "maineffect": "[Main] Suspend 1 of your opponents Digimon. Then, return 1 of your opponent's suspended Digimon to its owner's hand.",
            "soureeffect": "[Security] Activate this card's [Main] effect."
        },
        {
            "name": "Hell Masquerade",
            "type": "Option",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-15.jpg",
            "cardnumber": "ST9-15",
            "play_cost": 1,
            "maineffect": "[Main] 1 of your Digimon gets +2000 DP for the turn. Then, if you have a blue Digimon in play, 1 of your Digimon gains ＜Piercing＞ (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would) for the turn.",
            "soureeffect": "[Security] Add this card to its owner's hand."
        },
        {
            "name": "Hell Masquerade",
            "type": "Option",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-15.jpg",
            "cardnumber": "ST9-15",
            "play_cost": 1,
            "maineffect": "[Main] 1 of your Digimon gets +2000 DP for the turn. Then, if you have a blue Digimon in play, 1 of your Digimon gains ＜Piercing＞ (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would) for the turn.",
            "soureeffect": "[Security] Add this card to its owner's hand."
        },
        {
            "name": "Hell Masquerade",
            "type": "Option",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-15.jpg",
            "cardnumber": "ST9-15",
            "play_cost": 1,
            "maineffect": "[Main] 1 of your Digimon gets +2000 DP for the turn. Then, if you have a blue Digimon in play, 1 of your Digimon gains ＜Piercing＞ (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would) for the turn.",
            "soureeffect": "[Security] Add this card to its owner's hand."
        },
        {
            "name": "Hell Masquerade",
            "type": "Option",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-15.jpg",
            "cardnumber": "ST9-15",
            "play_cost": 1,
            "maineffect": "[Main] 1 of your Digimon gets +2000 DP for the turn. Then, if you have a blue Digimon in play, 1 of your Digimon gains ＜Piercing＞ (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would) for the turn.",
            "soureeffect": "[Security] Add this card to its owner's hand."
        },
        {
            "name": "Veemon",
            "type": "Digimon",
            "color": "Blue",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-02.jpg",
            "cardnumber": "ST9-02",
            "stage": "Rookie",
            "attribute": "Free",
            "digi_type": "Mini Dragon",
            "dp": 2000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3,
            "maineffect": "[On Play] Reveal the top 3 cards of your deck. Add 1 card with the [Free] trait among them to your hand. Place the remaining cards at the bottom of your deck in any order."
        },
        {
            "name": "Veemon",
            "type": "Digimon",
            "color": "Blue",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-02.jpg",
            "cardnumber": "ST9-02",
            "stage": "Rookie",
            "attribute": "Free",
            "digi_type": "Mini Dragon",
            "dp": 2000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3,
            "maineffect": "[On Play] Reveal the top 3 cards of your deck. Add 1 card with the [Free] trait among them to your hand. Place the remaining cards at the bottom of your deck in any order."
        },
        {
            "name": "Betamon",
            "type": "Digimon",
            "color": "Blue",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-03.jpg",
            "cardnumber": "ST9-03",
            "stage": "Rookie",
            "attribute": "Virus",
            "digi_type": "Amphibian",
            "dp": 4000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3
        },
        {
            "name": "Betamon",
            "type": "Digimon",
            "color": "Blue",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-03.jpg",
            "cardnumber": "ST9-03",
            "stage": "Rookie",
            "attribute": "Virus",
            "digi_type": "Amphibian",
            "dp": 4000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3
        },
        {
            "name": "Betamon",
            "type": "Digimon",
            "color": "Blue",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-03.jpg",
            "cardnumber": "ST9-03",
            "stage": "Rookie",
            "attribute": "Virus",
            "digi_type": "Amphibian",
            "dp": 4000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3
        },
        {
            "name": "Betamon",
            "type": "Digimon",
            "color": "Blue",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-03.jpg",
            "cardnumber": "ST9-03",
            "stage": "Rookie",
            "attribute": "Virus",
            "digi_type": "Amphibian",
            "dp": 4000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3
        },
        {
            "name": "KoKabuterimon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-07.jpg",
            "cardnumber": "ST9-07",
            "stage": "Rookie",
            "attribute": "Virus",
            "digi_type": "Insectoid",
            "dp": 2000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3,
            "maineffect": "[Opponent's Turn] While you have a blue Digimon in play, this Digimon gains ＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target)."
        },
        {
            "name": "KoKabuterimon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-07.jpg",
            "cardnumber": "ST9-07",
            "stage": "Rookie",
            "attribute": "Virus",
            "digi_type": "Insectoid",
            "dp": 2000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3,
            "maineffect": "[Opponent's Turn] While you have a blue Digimon in play, this Digimon gains ＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target)."
        },
        {
            "name": "KoKabuterimon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-07.jpg",
            "cardnumber": "ST9-07",
            "stage": "Rookie",
            "attribute": "Virus",
            "digi_type": "Insectoid",
            "dp": 2000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3,
            "maineffect": "[Opponent's Turn] While you have a blue Digimon in play, this Digimon gains ＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target)."
        },
        {
            "name": "KoKabuterimon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-07.jpg",
            "cardnumber": "ST9-07",
            "stage": "Rookie",
            "attribute": "Virus",
            "digi_type": "Insectoid",
            "dp": 2000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3,
            "maineffect": "[Opponent's Turn] While you have a blue Digimon in play, this Digimon gains ＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target)."
        },
        {
            "name": "Wormmon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-08.jpg",
            "cardnumber": "ST9-08",
            "stage": "Rookie",
            "attribute": "Free",
            "digi_type": "Larva",
            "dp": 3000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3,
            "soureeffect": "[End of Your Turn] You may DNA digivolve this Digimon and one of your other Digimon in play into a Digimon card in your hand by paying its DNA digivolve cost."
        },
        {
            "name": "Wormmon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-08.jpg",
            "cardnumber": "ST9-08",
            "stage": "Rookie",
            "attribute": "Free",
            "digi_type": "Larva",
            "dp": 3000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3,
            "soureeffect": "[End of Your Turn] You may DNA digivolve this Digimon and one of your other Digimon in play into a Digimon card in your hand by paying its DNA digivolve cost."
        },
        {
            "name": "Wormmon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-08.jpg",
            "cardnumber": "ST9-08",
            "stage": "Rookie",
            "attribute": "Free",
            "digi_type": "Larva",
            "dp": 3000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3,
            "soureeffect": "[End of Your Turn] You may DNA digivolve this Digimon and one of your other Digimon in play into a Digimon card in your hand by paying its DNA digivolve cost."
        },
        {
            "name": "Wormmon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-08.jpg",
            "cardnumber": "ST9-08",
            "stage": "Rookie",
            "attribute": "Free",
            "digi_type": "Larva",
            "dp": 3000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3,
            "soureeffect": "[End of Your Turn] You may DNA digivolve this Digimon and one of your other Digimon in play into a Digimon card in your hand by paying its DNA digivolve cost."
        },
        {
            "name": "ExVeemon",
            "type": "Digimon",
            "color": "Blue",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-04.jpg",
            "cardnumber": "ST9-04",
            "stage": "Champion",
            "attribute": "Free",
            "digi_type": "Mythical Beast",
            "dp": 4000,
            "play_cost": 4,
            "evolution_cost": 2,
            "level": 4,
            "maineffect": "When you would play this card from your hand, if you have a green Digimon in play, reduce its play cost by 1.",
            "soureeffect": "[When Attacking] If you have a green Digimon in play, this Digimon gets +1000 DP for the turn."
        },
        {
            "name": "ExVeemon",
            "type": "Digimon",
            "color": "Blue",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-04.jpg",
            "cardnumber": "ST9-04",
            "stage": "Champion",
            "attribute": "Free",
            "digi_type": "Mythical Beast",
            "dp": 4000,
            "play_cost": 4,
            "evolution_cost": 2,
            "level": 4,
            "maineffect": "When you would play this card from your hand, if you have a green Digimon in play, reduce its play cost by 1.",
            "soureeffect": "[When Attacking] If you have a green Digimon in play, this Digimon gets +1000 DP for the turn."
        },
        {
            "name": "ExVeemon",
            "type": "Digimon",
            "color": "Blue",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-04.jpg",
            "cardnumber": "ST9-04",
            "stage": "Champion",
            "attribute": "Free",
            "digi_type": "Mythical Beast",
            "dp": 4000,
            "play_cost": 4,
            "evolution_cost": 2,
            "level": 4,
            "maineffect": "When you would play this card from your hand, if you have a green Digimon in play, reduce its play cost by 1.",
            "soureeffect": "[When Attacking] If you have a green Digimon in play, this Digimon gets +1000 DP for the turn."
        },
        {
            "name": "ExVeemon",
            "type": "Digimon",
            "color": "Blue",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-04.jpg",
            "cardnumber": "ST9-04",
            "stage": "Champion",
            "attribute": "Free",
            "digi_type": "Mythical Beast",
            "dp": 4000,
            "play_cost": 4,
            "evolution_cost": 2,
            "level": 4,
            "maineffect": "When you would play this card from your hand, if you have a green Digimon in play, reduce its play cost by 1.",
            "soureeffect": "[When Attacking] If you have a green Digimon in play, this Digimon gets +1000 DP for the turn."
        },
        {
            "name": "Stingmon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-09.jpg",
            "cardnumber": "ST9-09",
            "stage": "Champion",
            "attribute": "Free",
            "digi_type": "Insectoid",
            "dp": 4000,
            "play_cost": 4,
            "evolution_cost": 2,
            "level": 4,
            "maineffect": "When you would play this card from your hand, if you have a blue Digimon in play, reduce its play cost by 1.",
            "soureeffect": "[When Attacking] If you have a blue Digimon in play, ＜Draw 1＞ (Draw 1 card from your deck)."
        },
        {
            "name": "Stingmon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-09.jpg",
            "cardnumber": "ST9-09",
            "stage": "Champion",
            "attribute": "Free",
            "digi_type": "Insectoid",
            "dp": 4000,
            "play_cost": 4,
            "evolution_cost": 2,
            "level": 4,
            "maineffect": "When you would play this card from your hand, if you have a blue Digimon in play, reduce its play cost by 1.",
            "soureeffect": "[When Attacking] If you have a blue Digimon in play, ＜Draw 1＞ (Draw 1 card from your deck)."
        },
        {
            "name": "Stingmon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-09.jpg",
            "cardnumber": "ST9-09",
            "stage": "Champion",
            "attribute": "Free",
            "digi_type": "Insectoid",
            "dp": 4000,
            "play_cost": 4,
            "evolution_cost": 2,
            "level": 4,
            "maineffect": "When you would play this card from your hand, if you have a blue Digimon in play, reduce its play cost by 1.",
            "soureeffect": "[When Attacking] If you have a blue Digimon in play, ＜Draw 1＞ (Draw 1 card from your deck)."
        },
        {
            "name": "Stingmon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-09.jpg",
            "cardnumber": "ST9-09",
            "stage": "Champion",
            "attribute": "Free",
            "digi_type": "Insectoid",
            "dp": 4000,
            "play_cost": 4,
            "evolution_cost": 2,
            "level": 4,
            "maineffect": "When you would play this card from your hand, if you have a blue Digimon in play, reduce its play cost by 1.",
            "soureeffect": "[When Attacking] If you have a blue Digimon in play, ＜Draw 1＞ (Draw 1 card from your deck)."
        },
        {
            "name": "Snimon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-10.jpg",
            "cardnumber": "ST9-10",
            "stage": "Champion",
            "attribute": "Vaccine",
            "digi_type": "Insectoid",
            "dp": 4000,
            "play_cost": 6,
            "evolution_cost": 2,
            "level": 4,
            "maineffect": "[Security] At the end of the battle, play this card without paying its memory cost. [On Play] Suspend 1 of your opponent's Digimon."
        },
        {
            "name": "Snimon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-10.jpg",
            "cardnumber": "ST9-10",
            "stage": "Champion",
            "attribute": "Vaccine",
            "digi_type": "Insectoid",
            "dp": 4000,
            "play_cost": 6,
            "evolution_cost": 2,
            "level": 4,
            "maineffect": "[Security] At the end of the battle, play this card without paying its memory cost. [On Play] Suspend 1 of your opponent's Digimon."
        },
        {
            "name": "Paildramon",
            "type": "Digimon",
            "color": "Blue",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-05.jpg",
            "cardnumber": "ST9-05",
            "stage": "Champion",
            "attribute": "Free",
            "digi_type": "Dragonkin",
            "dp": 8000,
            "play_cost": 8,
            "evolution_cost": 4,
            "level": 5,
            "maineffect": "[When Digivolving] When DNA digivolving, return 1 of your opponent's Digimon with 6000 DP or less to the bottom of its owner's deck. [When Attacking] [Once Per Turn] Unsuspend this Digimon."
        },
        {
            "name": "Paildramon",
            "type": "Digimon",
            "color": "Blue",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-05.jpg",
            "cardnumber": "ST9-05",
            "stage": "Champion",
            "attribute": "Free",
            "digi_type": "Dragonkin",
            "dp": 8000,
            "play_cost": 8,
            "evolution_cost": 4,
            "level": 5,
            "maineffect": "[When Digivolving] When DNA digivolving, return 1 of your opponent's Digimon with 6000 DP or less to the bottom of its owner's deck. [When Attacking] [Once Per Turn] Unsuspend this Digimon."
        },
        {
            "name": "Dinobeemon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-11.jpg",
            "cardnumber": "ST9-11",
            "stage": "Ultimate",
            "attribute": "Free",
            "digi_type": "Mutant",
            "dp": 8000,
            "play_cost": 8,
            "evolution_cost": 4,
            "level": 5,
            "maineffect": "[When Digivolving] Suspend 1 of your opponent's Digimon. When DNA digivolving, that Digimon doesn't unsuspend during its owner's next unsuspend phase.",
            "soureeffect": "[Your Turn] This Digimon gets +1000 DP for each of its colours."
        },
        {
            "name": "Dinobeemon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-11.jpg",
            "cardnumber": "ST9-11",
            "stage": "Ultimate",
            "attribute": "Free",
            "digi_type": "Mutant",
            "dp": 8000,
            "play_cost": 8,
            "evolution_cost": 4,
            "level": 5,
            "maineffect": "[When Digivolving] Suspend 1 of your opponent's Digimon. When DNA digivolving, that Digimon doesn't unsuspend during its owner's next unsuspend phase.",
            "soureeffect": "[Your Turn] This Digimon gets +1000 DP for each of its colours."
        },
        {
            "name": "Dinobeemon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-11.jpg",
            "cardnumber": "ST9-11",
            "stage": "Ultimate",
            "attribute": "Free",
            "digi_type": "Mutant",
            "dp": 8000,
            "play_cost": 8,
            "evolution_cost": 4,
            "level": 5,
            "maineffect": "[When Digivolving] Suspend 1 of your opponent's Digimon. When DNA digivolving, that Digimon doesn't unsuspend during its owner's next unsuspend phase.",
            "soureeffect": "[Your Turn] This Digimon gets +1000 DP for each of its colours."
        },
        {
            "name": "Dinobeemon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-11.jpg",
            "cardnumber": "ST9-11",
            "stage": "Ultimate",
            "attribute": "Free",
            "digi_type": "Mutant",
            "dp": 8000,
            "play_cost": 8,
            "evolution_cost": 4,
            "level": 5,
            "maineffect": "[When Digivolving] Suspend 1 of your opponent's Digimon. When DNA digivolving, that Digimon doesn't unsuspend during its owner's next unsuspend phase.",
            "soureeffect": "[Your Turn] This Digimon gets +1000 DP for each of its colours."
        },
        {
            "name": "JewelBeemon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-12.jpg",
            "cardnumber": "ST9-12",
            "stage": "Ultimate",
            "attribute": "Vaccine",
            "digi_type": "Insectoid",
            "dp": 7000,
            "play_cost": 6,
            "evolution_cost": 3,
            "level": 5
        },
        {
            "name": "JewelBeemon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-12.jpg",
            "cardnumber": "ST9-12",
            "stage": "Ultimate",
            "attribute": "Vaccine",
            "digi_type": "Insectoid",
            "dp": 7000,
            "play_cost": 6,
            "evolution_cost": 3,
            "level": 5
        },
        {
            "name": "JewelBeemon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-12.jpg",
            "cardnumber": "ST9-12",
            "stage": "Ultimate",
            "attribute": "Vaccine",
            "digi_type": "Insectoid",
            "dp": 7000,
            "play_cost": 6,
            "evolution_cost": 3,
            "level": 5
        },
        {
            "name": "JewelBeemon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-12.jpg",
            "cardnumber": "ST9-12",
            "stage": "Ultimate",
            "attribute": "Vaccine",
            "digi_type": "Insectoid",
            "dp": 7000,
            "play_cost": 6,
            "evolution_cost": 3,
            "level": 5
        },
        {
            "name": "Imperialdramon Dragon Mode",
            "type": "Digimon",
            "color": "Blue",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-06.jpg",
            "cardnumber": "ST9-06",
            "stage": "Ultimate",
            "attribute": "Free",
            "digi_type": "Ancient Dragon",
            "dp": 12000,
            "play_cost": 13,
            "evolution_cost": 4,
            "level": 6,
            "maineffect": "[When Digivolving] You may play 1 level 4 or lower blue Digimon card and/or 1 level 4 or lower green Digimon card from this Digimon's digivolution cards without paying their memory costs."
        },
        {
            "name": "Imperialdramon Dragon Mode",
            "type": "Digimon",
            "color": "Blue",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-06.jpg",
            "cardnumber": "ST9-06",
            "stage": "Ultimate",
            "attribute": "Free",
            "digi_type": "Ancient Dragon",
            "dp": 12000,
            "play_cost": 13,
            "evolution_cost": 4,
            "level": 6,
            "maineffect": "[When Digivolving] You may play 1 level 4 or lower blue Digimon card and/or 1 level 4 or lower green Digimon card from this Digimon's digivolution cards without paying their memory costs."
        },
        {
            "name": "GranKuwagamon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-13.jpg",
            "cardnumber": "ST9-13",
            "stage": "Ultimate",
            "attribute": "Free",
            "digi_type": "Insectoid",
            "dp": 11000,
            "play_cost": 12,
            "evolution_cost": 3,
            "level": 6,
            "maineffect": "＜Security Attack +1＞ (This Digimon checks 1 additional security card) [When Digivolving] This Digimon gets +4000 DP for the turn."
        },
        {
            "name": "GranKuwagamon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-13.jpg",
            "cardnumber": "ST9-13",
            "stage": "Ultimate",
            "attribute": "Free",
            "digi_type": "Insectoid",
            "dp": 11000,
            "play_cost": 12,
            "evolution_cost": 3,
            "level": 6,
            "maineffect": "＜Security Attack +1＞ (This Digimon checks 1 additional security card) [When Digivolving] This Digimon gets +4000 DP for the turn."
        },
        {
            "name": "GranKuwagamon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-13.jpg",
            "cardnumber": "ST9-13",
            "stage": "Ultimate",
            "attribute": "Free",
            "digi_type": "Insectoid",
            "dp": 11000,
            "play_cost": 12,
            "evolution_cost": 3,
            "level": 6,
            "maineffect": "＜Security Attack +1＞ (This Digimon checks 1 additional security card) [When Digivolving] This Digimon gets +4000 DP for the turn."
        },
        {
            "name": "GranKuwagamon",
            "type": "Digimon",
            "color": "Green",
            "image_url": "https://images.digimoncard.io/images/cards/ST9-13.jpg",
            "cardnumber": "ST9-13",
            "stage": "Ultimate",
            "attribute": "Free",
            "digi_type": "Insectoid",
            "dp": 11000,
            "play_cost": 12,
            "evolution_cost": 3,
            "level": 6,
            "maineffect": "＜Security Attack +1＞ (This Digimon checks 1 additional security card) [When Digivolving] This Digimon gets +4000 DP for the turn."
        }
    ]
;

export const starterGallantmon: CardType[] = [
        {
            "name": "Gigimon",
            "type": "Digi-Egg",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-01.jpg",
            "cardnumber": "ST7-01",
            "stage": "In-Training",
            "digi_type": "Lesser",
            "level": 2,
            "soureeffect": "[Your Turn] [Once Per Turn] When an opponent's Digimon is deleted, this Digimon gets +2000 DP for the turn."
        },
        {
            "name": "Gigimon",
            "type": "Digi-Egg",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-01.jpg",
            "cardnumber": "ST7-01",
            "stage": "In-Training",
            "digi_type": "Lesser",
            "level": 2,
            "soureeffect": "[Your Turn] [Once Per Turn] When an opponent's Digimon is deleted, this Digimon gets +2000 DP for the turn."
        },
        {
            "name": "Gigimon",
            "type": "Digi-Egg",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-01.jpg",
            "cardnumber": "ST7-01",
            "stage": "In-Training",
            "digi_type": "Lesser",
            "level": 2,
            "soureeffect": "[Your Turn] [Once Per Turn] When an opponent's Digimon is deleted, this Digimon gets +2000 DP for the turn."
        },
        {
            "name": "Gigimon",
            "type": "Digi-Egg",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-01.jpg",
            "cardnumber": "ST7-01",
            "stage": "In-Training",
            "digi_type": "Lesser",
            "level": 2,
            "soureeffect": "[Your Turn] [Once Per Turn] When an opponent's Digimon is deleted, this Digimon gets +2000 DP for the turn."
        },
        {
            "name": "Gaia Force",
            "type": "Option",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST1-16.jpg",
            "cardnumber": "ST1-16",
            "play_cost": 8,
            "maineffect": "[Main] Delete 1 of your opponent's Digimon.",
            "soureeffect": "[Security] Activate this card's [Main] effect."
        },
        {
            "name": "Gaia Force",
            "type": "Option",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST1-16.jpg",
            "cardnumber": "ST1-16",
            "play_cost": 8,
            "maineffect": "[Main] Delete 1 of your opponent's Digimon.",
            "soureeffect": "[Security] Activate this card's [Main] effect."
        },
        {
            "name": "Gaia Force",
            "type": "Option",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST1-16.jpg",
            "cardnumber": "ST1-16",
            "play_cost": 8,
            "maineffect": "[Main] Delete 1 of your opponent's Digimon.",
            "soureeffect": "[Security] Activate this card's [Main] effect."
        },
        {
            "name": "Gaia Force",
            "type": "Option",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST1-16.jpg",
            "cardnumber": "ST1-16",
            "play_cost": 8,
            "maineffect": "[Main] Delete 1 of your opponent's Digimon.",
            "soureeffect": "[Security] Activate this card's [Main] effect."
        },
        {
            "name": "Lightning Joust",
            "type": "Option",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-11.jpg",
            "cardnumber": "ST7-11",
            "play_cost": 1,
            "maineffect": "[Main] 1 of your Digimon gets +2000 DP for the turn. Then, if the number of cards in your security stack is less than or equal to your opponent's, 1 of your Digimon gains ＜Security Attack +1＞ (This Digimon checks 1 additional security card) for the turn.",
            "soureeffect": "[Security] Add this card to its owner's hand."
        },
        {
            "name": "Lightning Joust",
            "type": "Option",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-11.jpg",
            "cardnumber": "ST7-11",
            "play_cost": 1,
            "maineffect": "[Main] 1 of your Digimon gets +2000 DP for the turn. Then, if the number of cards in your security stack is less than or equal to your opponent's, 1 of your Digimon gains ＜Security Attack +1＞ (This Digimon checks 1 additional security card) for the turn.",
            "soureeffect": "[Security] Add this card to its owner's hand."
        },
        {
            "name": "Atomic Blaster",
            "type": "Option",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-12.jpg",
            "cardnumber": "ST7-12",
            "play_cost": 5,
            "maineffect": "[Main] Choose any number of your opponent's Digimon whose total DP adds up to 8000 or less and delete them.",
            "soureeffect": "[Security] Activate this card's [Main] effect."
        },
        {
            "name": "Atomic Blaster",
            "type": "Option",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-12.jpg",
            "cardnumber": "ST7-12",
            "play_cost": 5,
            "maineffect": "[Main] Choose any number of your opponent's Digimon whose total DP adds up to 8000 or less and delete them.",
            "soureeffect": "[Security] Activate this card's [Main] effect."
        },
        {
            "name": "Atomic Blaster",
            "type": "Option",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-12.jpg",
            "cardnumber": "ST7-12",
            "play_cost": 5,
            "maineffect": "[Main] Choose any number of your opponent's Digimon whose total DP adds up to 8000 or less and delete them.",
            "soureeffect": "[Security] Activate this card's [Main] effect."
        },
        {
            "name": "Atomic Blaster",
            "type": "Option",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-12.jpg",
            "cardnumber": "ST7-12",
            "play_cost": 5,
            "maineffect": "[Main] Choose any number of your opponent's Digimon whose total DP adds up to 8000 or less and delete them.",
            "soureeffect": "[Security] Activate this card's [Main] effect."
        },
        {
            "name": "Monodramon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/BT1-009.jpg",
            "cardnumber": "BT1-009",
            "stage": "Rookie",
            "attribute": "Vaccine",
            "digi_type": "Mini Dragon",
            "dp": 3000,
            "play_cost": 2,
            "evolution_cost": 0,
            "level": 3
        },
        {
            "name": "Monodramon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/BT1-009.jpg",
            "cardnumber": "BT1-009",
            "stage": "Rookie",
            "attribute": "Vaccine",
            "digi_type": "Mini Dragon",
            "dp": 3000,
            "play_cost": 2,
            "evolution_cost": 0,
            "level": 3
        },
        {
            "name": "Monodramon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/BT1-009.jpg",
            "cardnumber": "BT1-009",
            "stage": "Rookie",
            "attribute": "Vaccine",
            "digi_type": "Mini Dragon",
            "dp": 3000,
            "play_cost": 2,
            "evolution_cost": 0,
            "level": 3
        },
        {
            "name": "Monodramon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/BT1-009.jpg",
            "cardnumber": "BT1-009",
            "stage": "Rookie",
            "attribute": "Vaccine",
            "digi_type": "Mini Dragon",
            "dp": 3000,
            "play_cost": 2,
            "evolution_cost": 0,
            "level": 3
        },
        {
            "name": "Agumon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-02.jpg",
            "cardnumber": "ST7-02",
            "stage": "Rookie",
            "attribute": "Vaccine",
            "digi_type": "Dinosaur",
            "dp": 2000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3,
            "soureeffect": "[When Attacking] When this Digimon attacks a player, it gets +2000 DP for the turn."
        },
        {
            "name": "Agumon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-02.jpg",
            "cardnumber": "ST7-02",
            "stage": "Rookie",
            "attribute": "Vaccine",
            "digi_type": "Dinosaur",
            "dp": 2000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3,
            "soureeffect": "[When Attacking] When this Digimon attacks a player, it gets +2000 DP for the turn."
        },
        {
            "name": "Agumon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-02.jpg",
            "cardnumber": "ST7-02",
            "stage": "Rookie",
            "attribute": "Vaccine",
            "digi_type": "Dinosaur",
            "dp": 2000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3,
            "soureeffect": "[When Attacking] When this Digimon attacks a player, it gets +2000 DP for the turn."
        },
        {
            "name": "Agumon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-02.jpg",
            "cardnumber": "ST7-02",
            "stage": "Rookie",
            "attribute": "Vaccine",
            "digi_type": "Dinosaur",
            "dp": 2000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3,
            "soureeffect": "[When Attacking] When this Digimon attacks a player, it gets +2000 DP for the turn."
        },
        {
            "name": "Guilmon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-03.jpg",
            "cardnumber": "ST7-03",
            "stage": "Rookie",
            "attribute": "Virus",
            "digi_type": "Reptile",
            "dp": 2000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3,
            "maineffect": "[Your Turn] If your opponent has a level 6 or higher Digimon in play, this Digimon can digivolve into a [Gallantmon] in your hand for a memory cost of 4, ignoring its digivolution requirements.",
            "soureeffect": "[Your Turn] [Once Per Turn] When an opponent's Digimon is deleted, ＜Draw 1＞ (Draw 1 card from your deck)."
        },
        {
            "name": "Guilmon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-03.jpg",
            "cardnumber": "ST7-03",
            "stage": "Rookie",
            "attribute": "Virus",
            "digi_type": "Reptile",
            "dp": 2000,
            "play_cost": 3,
            "evolution_cost": 0,
            "level": 3,
            "maineffect": "[Your Turn] If your opponent has a level 6 or higher Digimon in play, this Digimon can digivolve into a [Gallantmon] in your hand for a memory cost of 4, ignoring its digivolution requirements.",
            "soureeffect": "[Your Turn] [Once Per Turn] When an opponent's Digimon is deleted, ＜Draw 1＞ (Draw 1 card from your deck)."
        },
        {
            "name": "Biyomon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-04.jpg",
            "cardnumber": "ST7-04",
            "stage": "Rookie",
            "attribute": "Vaccine",
            "digi_type": "Bird",
            "dp": 3000,
            "play_cost": 4,
            "evolution_cost": 0,
            "level": 3,
            "maineffect": "＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target). [Your Turn] This Digimon can't attack players."
        },
        {
            "name": "Biyomon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-04.jpg",
            "cardnumber": "ST7-04",
            "stage": "Rookie",
            "attribute": "Vaccine",
            "digi_type": "Bird",
            "dp": 3000,
            "play_cost": 4,
            "evolution_cost": 0,
            "level": 3,
            "maineffect": "＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target). [Your Turn] This Digimon can't attack players."
        },
        {
            "name": "Biyomon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-04.jpg",
            "cardnumber": "ST7-04",
            "stage": "Rookie",
            "attribute": "Vaccine",
            "digi_type": "Bird",
            "dp": 3000,
            "play_cost": 4,
            "evolution_cost": 0,
            "level": 3,
            "maineffect": "＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target). [Your Turn] This Digimon can't attack players."
        },
        {
            "name": "Biyomon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-04.jpg",
            "cardnumber": "ST7-04",
            "stage": "Rookie",
            "attribute": "Vaccine",
            "digi_type": "Bird",
            "dp": 3000,
            "play_cost": 4,
            "evolution_cost": 0,
            "level": 3,
            "maineffect": "＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target). [Your Turn] This Digimon can't attack players."
        },
        {
            "name": "DarkTyrannomon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/BT1-019.jpg",
            "cardnumber": "BT1-019",
            "stage": "Champion",
            "attribute": "Virus",
            "digi_type": "Dinosaur",
            "dp": 6000,
            "play_cost": 6,
            "evolution_cost": 1,
            "level": 4
        },
        {
            "name": "DarkTyrannomon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/BT1-019.jpg",
            "cardnumber": "BT1-019",
            "stage": "Champion",
            "attribute": "Virus",
            "digi_type": "Dinosaur",
            "dp": 6000,
            "play_cost": 6,
            "evolution_cost": 1,
            "level": 4
        },
        {
            "name": "DarkTyrannomon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/BT1-019.jpg",
            "cardnumber": "BT1-019",
            "stage": "Champion",
            "attribute": "Virus",
            "digi_type": "Dinosaur",
            "dp": 6000,
            "play_cost": 6,
            "evolution_cost": 1,
            "level": 4
        },
        {
            "name": "DarkTyrannomon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/BT1-019.jpg",
            "cardnumber": "BT1-019",
            "stage": "Champion",
            "attribute": "Virus",
            "digi_type": "Dinosaur",
            "dp": 6000,
            "play_cost": 6,
            "evolution_cost": 1,
            "level": 4
        },
        {
            "name": "Growlmon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-05.jpg",
            "cardnumber": "ST7-05",
            "stage": "Champion",
            "attribute": "Virus",
            "digi_type": "Dark Dragon",
            "dp": 5000,
            "play_cost": 4,
            "evolution_cost": 2,
            "level": 4,
            "soureeffect": "[Your Turn] [Once Per Turn] When an opponent's Digimon is deleted, gain 1 memory."
        },
        {
            "name": "Growlmon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-05.jpg",
            "cardnumber": "ST7-05",
            "stage": "Champion",
            "attribute": "Virus",
            "digi_type": "Dark Dragon",
            "dp": 5000,
            "play_cost": 4,
            "evolution_cost": 2,
            "level": 4,
            "soureeffect": "[Your Turn] [Once Per Turn] When an opponent's Digimon is deleted, gain 1 memory."
        },
        {
            "name": "GeoGreymon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-06.jpg",
            "cardnumber": "ST7-06",
            "stage": "Champion",
            "attribute": "Vaccine",
            "digi_type": "Dinosaur",
            "dp": 5000,
            "play_cost": 6,
            "evolution_cost": 2,
            "level": 4,
            "maineffect": "[Security] At the end of the battle, play this card without paying its memory cost. [On Play] Delete 1 of your opponent's Digimon with 4000 DP or less."
        },
        {
            "name": "GeoGreymon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-06.jpg",
            "cardnumber": "ST7-06",
            "stage": "Champion",
            "attribute": "Vaccine",
            "digi_type": "Dinosaur",
            "dp": 5000,
            "play_cost": 6,
            "evolution_cost": 2,
            "level": 4,
            "maineffect": "[Security] At the end of the battle, play this card without paying its memory cost. [On Play] Delete 1 of your opponent's Digimon with 4000 DP or less."
        },
        {
            "name": "GeoGreymon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-06.jpg",
            "cardnumber": "ST7-06",
            "stage": "Champion",
            "attribute": "Vaccine",
            "digi_type": "Dinosaur",
            "dp": 5000,
            "play_cost": 6,
            "evolution_cost": 2,
            "level": 4,
            "maineffect": "[Security] At the end of the battle, play this card without paying its memory cost. [On Play] Delete 1 of your opponent's Digimon with 4000 DP or less."
        },
        {
            "name": "GeoGreymon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-06.jpg",
            "cardnumber": "ST7-06",
            "stage": "Champion",
            "attribute": "Vaccine",
            "digi_type": "Dinosaur",
            "dp": 5000,
            "play_cost": 6,
            "evolution_cost": 2,
            "level": 4,
            "maineffect": "[Security] At the end of the battle, play this card without paying its memory cost. [On Play] Delete 1 of your opponent's Digimon with 4000 DP or less."
        },
        {
            "name": "Groundramon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/BT1-020.jpg",
            "cardnumber": "BT1-020",
            "stage": "Ultimate",
            "attribute": "Virus",
            "digi_type": "Earth Dragon",
            "dp": 6000,
            "play_cost": 5,
            "evolution_cost": 2,
            "level": 5
        },
        {
            "name": "Groundramon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/BT1-020.jpg",
            "cardnumber": "BT1-020",
            "stage": "Ultimate",
            "attribute": "Virus",
            "digi_type": "Earth Dragon",
            "dp": 6000,
            "play_cost": 5,
            "evolution_cost": 2,
            "level": 5
        },
        {
            "name": "RizeGreymon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-07.jpg",
            "cardnumber": "ST7-07",
            "stage": "Ultimate",
            "attribute": "Vaccine",
            "digi_type": "Cyborg",
            "dp": 7000,
            "play_cost": 7,
            "evolution_cost": 3,
            "level": 5,
            "maineffect": "[On Play] Delete 1 of your opponent's Digimon with 5000 DP or less."
        },
        {
            "name": "RizeGreymon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-07.jpg",
            "cardnumber": "ST7-07",
            "stage": "Ultimate",
            "attribute": "Vaccine",
            "digi_type": "Cyborg",
            "dp": 7000,
            "play_cost": 7,
            "evolution_cost": 3,
            "level": 5,
            "maineffect": "[On Play] Delete 1 of your opponent's Digimon with 5000 DP or less."
        },
        {
            "name": "RizeGreymon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-07.jpg",
            "cardnumber": "ST7-07",
            "stage": "Ultimate",
            "attribute": "Vaccine",
            "digi_type": "Cyborg",
            "dp": 7000,
            "play_cost": 7,
            "evolution_cost": 3,
            "level": 5,
            "maineffect": "[On Play] Delete 1 of your opponent's Digimon with 5000 DP or less."
        },
        {
            "name": "RizeGreymon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-07.jpg",
            "cardnumber": "ST7-07",
            "stage": "Ultimate",
            "attribute": "Vaccine",
            "digi_type": "Cyborg",
            "dp": 7000,
            "play_cost": 7,
            "evolution_cost": 3,
            "level": 5,
            "maineffect": "[On Play] Delete 1 of your opponent's Digimon with 5000 DP or less."
        },
        {
            "name": "WarGrowlmon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-08.jpg",
            "cardnumber": "ST7-08",
            "stage": "Ultimate",
            "attribute": "Virus",
            "digi_type": "Cyborg",
            "dp": 8000,
            "play_cost": 8,
            "evolution_cost": 3,
            "level": 5,
            "maineffect": "[When Attacking] Delete 1 of your opponent's Digimon with 3000 DP or less.",
            "soureeffect": "[Your Turn] [Once Per Turn] When an opponent's Digimon is deleted, this Digimon gains ＜Security Attack +1＞ (This Digimon checks 1 additional security card)."
        },
        {
            "name": "WarGrowlmon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-08.jpg",
            "cardnumber": "ST7-08",
            "stage": "Ultimate",
            "attribute": "Virus",
            "digi_type": "Cyborg",
            "dp": 8000,
            "play_cost": 8,
            "evolution_cost": 3,
            "level": 5,
            "maineffect": "[When Attacking] Delete 1 of your opponent's Digimon with 3000 DP or less.",
            "soureeffect": "[Your Turn] [Once Per Turn] When an opponent's Digimon is deleted, this Digimon gains ＜Security Attack +1＞ (This Digimon checks 1 additional security card)."
        },
        {
            "name": "WarGrowlmon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-08.jpg",
            "cardnumber": "ST7-08",
            "stage": "Ultimate",
            "attribute": "Virus",
            "digi_type": "Cyborg",
            "dp": 8000,
            "play_cost": 8,
            "evolution_cost": 3,
            "level": 5,
            "maineffect": "[When Attacking] Delete 1 of your opponent's Digimon with 3000 DP or less.",
            "soureeffect": "[Your Turn] [Once Per Turn] When an opponent's Digimon is deleted, this Digimon gains ＜Security Attack +1＞ (This Digimon checks 1 additional security card)."
        },
        {
            "name": "WarGrowlmon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-08.jpg",
            "cardnumber": "ST7-08",
            "stage": "Ultimate",
            "attribute": "Virus",
            "digi_type": "Cyborg",
            "dp": 8000,
            "play_cost": 8,
            "evolution_cost": 3,
            "level": 5,
            "maineffect": "[When Attacking] Delete 1 of your opponent's Digimon with 3000 DP or less.",
            "soureeffect": "[Your Turn] [Once Per Turn] When an opponent's Digimon is deleted, this Digimon gains ＜Security Attack +1＞ (This Digimon checks 1 additional security card)."
        },
        {
            "name": "Gallantmon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-09.jpg",
            "cardnumber": "ST7-09",
            "stage": "Champion",
            "attribute": "Virus",
            "digi_type": "Holy Warrior",
            "dp": 11000,
            "play_cost": 11,
            "evolution_cost": 3,
            "level": 6,
            "maineffect": "＜Security Attack +1＞ (This Digimon checks 1 additional security card) [When Attacking] Delete 1 of your opponent's Digimon with 4000 DP or less. If no Digimon was deleted by this effect, this Digimon gets +3000 DP for the turn."
        },
        {
            "name": "Gallantmon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-09.jpg",
            "cardnumber": "ST7-09",
            "stage": "Champion",
            "attribute": "Virus",
            "digi_type": "Holy Warrior",
            "dp": 11000,
            "play_cost": 11,
            "evolution_cost": 3,
            "level": 6,
            "maineffect": "＜Security Attack +1＞ (This Digimon checks 1 additional security card) [When Attacking] Delete 1 of your opponent's Digimon with 4000 DP or less. If no Digimon was deleted by this effect, this Digimon gets +3000 DP for the turn."
        },
        {
            "name": "ShineGreymon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-10.jpg",
            "cardnumber": "ST7-10",
            "stage": "Mega",
            "attribute": "Vaccine",
            "digi_type": "Light Dragon",
            "dp": 12000,
            "play_cost": 12,
            "evolution_cost": 4,
            "level": 6,
            "maineffect": "＜Security Attack +1＞ (This Digimon checks 1 additional security card). ＜Piercing＞ (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would)."
        },
        {
            "name": "ShineGreymon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-10.jpg",
            "cardnumber": "ST7-10",
            "stage": "Mega",
            "attribute": "Vaccine",
            "digi_type": "Light Dragon",
            "dp": 12000,
            "play_cost": 12,
            "evolution_cost": 4,
            "level": 6,
            "maineffect": "＜Security Attack +1＞ (This Digimon checks 1 additional security card). ＜Piercing＞ (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would)."
        },
        {
            "name": "ShineGreymon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-10.jpg",
            "cardnumber": "ST7-10",
            "stage": "Mega",
            "attribute": "Vaccine",
            "digi_type": "Light Dragon",
            "dp": 12000,
            "play_cost": 12,
            "evolution_cost": 4,
            "level": 6,
            "maineffect": "＜Security Attack +1＞ (This Digimon checks 1 additional security card). ＜Piercing＞ (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would)."
        },
        {
            "name": "ShineGreymon",
            "type": "Digimon",
            "color": "Red",
            "image_url": "https://images.digimoncard.io/images/cards/ST7-10.jpg",
            "cardnumber": "ST7-10",
            "stage": "Mega",
            "attribute": "Vaccine",
            "digi_type": "Light Dragon",
            "dp": 12000,
            "play_cost": 12,
            "evolution_cost": 4,
            "level": 6,
            "maineffect": "＜Security Attack +1＞ (This Digimon checks 1 additional security card). ＜Piercing＞ (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would)."
        }
    ]
;
